### ISSUE TITLE
chart not rendering since #130

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#138]
Ever since #130 was merged in, the chart has stopped rendering

```
Uncaught ReferenceError: $ is not defined
```

Struggling to recreate locally so will have to dig deeper

![screen shot 2016-03-25 at 5 25 43 pm](https://cloud.githubusercontent.com/assets/3509371/14040071/2f144016-f2af-11e5-8bbf-5ec3bbbb8037.png)

**Comment by rloomans** [comment]
Not pulling in JQuery in the right place?

## 

Robert Loomans

On 25 Mar 2016, at 17:30, Mike Villis <notifications@github.com<mailto:notifications@github.com>> wrote:

Ever since #130https://github.com/mvillis/measure-mate/pull/130 was merged in, the chart has stopped rendering

Uncaught ReferenceError: $ is not defined

Struggling to recreate locally so will have to dig deeper

[screen shot 2016-03-25 at 5 25 43 pm]https://cloud.githubusercontent.com/assets/3509371/14040071/2f144016-f2af-11e5-8bbf-5ec3bbbb8037.png

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://github.com/mvillis/measure-mate/issues/138

---

This e-mail is sent by Suncorp Group Limited ABN 66 145 290 124 or one of its related entities "Suncorp".
Suncorp may be contacted at Level 28, 266 George Street, Brisbane or on 13 11 55 or at suncorp.com.au.
The content of this e-mail is the view of the sender or stated author and does not necessarily reflect the view of Suncorp. The content, including attachments, is a confidential communication between Suncorp and the intended recipient. If you are not the intended recipient, any use, interference with, disclosure or copying of this e-mail, including attachments, is unauthorised and expressly prohibited. If you have received this e-mail in error please contact the sender immediately and delete the e-mail and any attachments from your system.

**Comment by mvillis** [comment]
will be something jquery yeah. will be interested to know if you can recreate it locally.

**Comment by rloomans** [comment]
Yeah, I can't see the graph. I haven't, however, looked at the browser console.

## 

Robert Loomans

On 25 Mar 2016, at 18:06, Mike Villis <notifications@github.com<mailto:notifications@github.com>> wrote:

will be something jquery yeah. will be interested to know if you can recreate it locally.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHubhttps://github.com/mvillis/measure-mate/issues/138#issuecomment-201193096

---

This e-mail is sent by Suncorp Group Limited ABN 66 145 290 124 or one of its related entities "Suncorp".
Suncorp may be contacted at Level 28, 266 George Street, Brisbane or on 13 11 55 or at suncorp.com.au.
The content of this e-mail is the view of the sender or stated author and does not necessarily reflect the view of Suncorp. The content, including attachments, is a confidential communication between Suncorp and the intended recipient. If you are not the intended recipient, any use, interference with, disclosure or copying of this e-mail, including attachments, is unauthorised and expressly prohibited. If you have received this e-mail in error please contact the sender immediately and delete the e-mail and any attachments from your system.

**Comment by rloomans** [comment]
It happens on herorku, but I don't get the same error running on my mac...
odd.

On 25 March 2016 at 18:06, Mike Villis notifications@github.com wrote:

> will be something jquery yeah. will be interested to know if you can
> recreate it locally.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/mvillis/measure-mate/issues/138#issuecomment-201193096

## 

Robert Loomans
robert@loomans.org

**Comment by rloomans** [comment]
Fixed for the moment by 8803db8b30a67c7450dd12b4c777ec5e7211f514
